Api:
  - name: keystore.createUser
    path: ext/keystore
    struct-args: false
    args: [["username", "string"], ["password", "string"]]
    struct-returns: false
    returns: [["success", "bool"], ["err", "error"]]
  - name: keystore.deleteUser
    path: ext/keystore
    struct-args: false
    args: [["username", "string"], ["password", "string"]]
    struct-returns: false
    returns: [["success", "bool"], ["err", "error"]]
  - name: keystore.exportUser
    path: ext/keystore
    struct-args: false
    args: [["username", "string"], ["password", "string"]]
    struct-returns: false
    returns: [["user", "string"], ["encoding", "string"], ["err", "error"]]
  - name: keystore.importUser
    path: ext/keystore
    struct-args: false
    args: [["username", "string"], ["password", "string"], ["user", "string"]]
    struct-returns: false
    returns: [["success", "bool"], ["err", "error"]]
  - name: keystore.listUsers
    path: ext/keystore
    struct-args: false
    args: [["username", "string"], ["password", "string"], ["user", "string"]]
    struct-returns: true
    returns: [["users", "ListUsersResponse"], ["err", "error"]]
